# *-* coding:utf-8 *-
'''
Created on 2020年5月4日

@author: Administrator
'''
list1 = ['BRANCH_NAME', 'CHANGE_ID', 'CHANGE_URL', 'CHANGE_TITLE', 'CHANGE_AUTHOR', 'CHANGE_AUTHOR_DISPLAY_NAME', 'CHANGE_AUTHOR_EMAIL', 'CHANGE_TARGET', 'BUILD_NUMBER', 'BUILD_ID', 'BUILD_DISPLAY_NAME','JOB_NAME','JOB_BASE_NAME','BUILD_TAG','EXECUTOR_NUMBER','NODE_NAME','NODE_LABELS','WORKSPACE','JENKINS_HOME','JENKINS_URL','BUILD_URL','JOB_URL','GIT_COMMIT','GIT_PREVIOUS_COMMIT','GIT_PREVIOUS_SUCCESSFUL_COMMIT','GIT_BRANCH','GIT_LOCAL_BRANCH','GIT_URL','GIT_COMMITTER_NAME','GIT_AUTHOR_NAME','GIT_COMMITTER_EMAIL','GIT_AUTHOR_EMAIL','SVN_REVISION','SVN_URL']
for i in list1:
    print("echo {name}=${value} >> ~/var.txt".format(name=i, value=i));

